#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      extension_name:
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}-${{ inputs.extension_name }}
  cancel-in-progress: true

jobs:
  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      duckdb_version: v1.1.2
      ci_tools_version: main
      override_ci_tools_repository: duckdb/extension-ci-tools
      extension_name: ${{ inputs.extension_name || 'httpfs' }}
      exclude_archs: 'linux_amd64_gcc4;linux_amd64;linux_arm64;osx_amd64;osx_arm64;windows_amd64_rtools;windows_amd64'

  duckdb-stable-deploy:
    name: Deploy extension binaries
    needs: duckdb-stable-build
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_deploy.yml@main
    secrets: inherit
    with:
      duckdb_version: v1.1.2
      extension_name: ${{ inputs.extension_name || 'httpfs' }}
      deploy_latest: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
      exclude_archs: 'linux_amd64_gcc4;linux_amd64;linux_arm64;osx_amd64;osx_arm64;windows_amd64_rtools;windows_amd64'
